### ISSUE TITLE
Is Alignment Layer (or Adaptive Pooling) implemented in this code?

### ISSUE THREAD

**Issue by scc-zju** [AaronHeee/MEAL#4]
I can't find the implementation of alignment layer in the code.
From the README.md, two demos are introduced, as follows:
- for single MEAL like teacher: vgg, student: vgg:
Due to the same architecture of student and teacher, `--out_layer [0,1,2,3,4]` doesn't need alignment layer.
- for ensemble MEAL like teachers: vgg19, densenet, dpn92,resnet18, preactresnet18; student:densenet:
` --out_layer [-1] ` means that only the last layer is applied to the learning of student. It's just similar to common knowledge distillation method, except random selection of multiple teachers.

So, alignment layer is not necessary to this task.
I am curious that how VGG-19 teacher can guide the learning of ResNet-50 student, where ResNet-50 and VGG-19 have different feature sizes(Experiments in Table 4 of paper). 
Could you share code of experiments in Table 4?

**Comment by szq0214** [comment]
Hi @scc-zju, you can also set --out_layer [0, 1, 2, 3, 4] for the second scenario, this code support that function through the alignment layers.
