### ISSUE TITLE
CUDA out of memory while executing Ensemble MEAL

### ISSUE THREAD

**Issue by aditipanda** [AaronHeee/MEAL#6]
I get this error even after reducing the '--batch_size' argument to as small as 8. 

It is mentioned to keep batch size as 256 for ensemble MEAL.

I am working on a **6 GB memory NVIDIA GPU** (GeForce GTX 980 Ti, with specifications:https://www.geforce.com/hardware/desktop-gpus/geforce-gtx-980-ti/specifications). 

Will it be possible to run the ensemble MEAL on this GPU? 

**RuntimeError: CUDA out of memory. Tried to allocate 55.00 MiB (GPU 0; 5.93 GiB total capacity; 5.10 GiB already allocated; 34.06 MiB free; 13.00 MiB cached)**

**Comment by szq0214** [comment]
@appyfizzA, I think 6 GB is a little bit too small and it will be better if you can use some more advanced GPUs.
