### ISSUE TITLE
Single MEAL vs Ensemble MEAL

### ISSUE THREAD

**Issue by aditipanda** [AaronHeee/MEAL#7]
Two different commands have been provided for running this code, single MEAL and ensemble MEAL.

What is the difference between the two? Does the single MEAL has one ensemble, and the ensemble MEAL has more than one ensembles? 

As mentioned in the paper, section 6.5, the "single model ensemble outputs the baseline model and performs well, which establishes the superiority of adversarial learning". Is this single model ensemble same as single MEAL?

**Comment by szq0214** [comment]
Hi @appyfizzA, your understanding is correct, single MEAL means we only use one teacher model for training and ensemble MEAL has more than one teacher with different structures. There, "single model ensemble" has the same meaning as "single MEAL".
