### ISSUE TITLE
Where is adversarial learning?

### ISSUE THREAD

**Issue by BinhuiXie** [AaronHeee/MEAL#9]
I would like to ask how author implement the adversarial training?  Do you implement it through alternately training discriminator and student network or  training them simultaneously using gradient reversal layer?

**Comment by szq0214** [comment]
Hi @binhuixie, the current implement trains discriminators and student jointly, we have an extension of this paper, in that one we discussed and investigated the conventional adversarial strategy (alternately update gradients of them). We will release the paper very soon. Please stay tuned and thanks!
